### ISSUE TITLE
XbsjEarthUI api

### ISSUE THREAD

**Issue by xiaoqufengdi** [cesiumlab/XbsjEarthUI#1]
XbsjEarthUI api文档在正常打包情况下没有打出来api文档
![image](https://user-images.githubusercontent.com/31072438/62592368-8e024800-b905-11e9-89d6-699d8210ff6d.png)

**Comment by vtxf** [comment]
这个问题已更正，请获取最新代码
或者直接执行 npm run doc

**Comment by vtxf** [comment]
也可以在这里看示例和文档：
http://cesiumlab.gitee.io/xbsjearthui
