### ISSUE TITLE
请问有没有增加完Pin点或是其他标记完成的事件

### ISSUE THREAD

**Issue by WanlyLu** [cesiumlab/XbsjEarthUI#109]
想要在增加完pin点之后给点一个默认高度，增加点用鼠标拾取的方式，可是没有找到增加完成的事件。尝试监控creating属性，但是发现这个属性一直是false，请问还有其他的方式能实现这个功能吗？

**Comment by vtxf** [comment]
拾取是creating为true，拾取完成，creating为false






唐晓飞
北京西部世界科技有限公司


 联系我









&nbsp;
