### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by aichangqing** [cesiumlab/XbsjEarthUI#2]
there are some errors in the running 'npm run build'.there are some Screenshots
![image](https://user-images.githubusercontent.com/22738120/63001153-86aee180-bea5-11e9-85af-2822e2eac466.png)

**Comment by vtxf** [comment]
try //127.0.0.1:81/dist/

**Comment by zivyangll** [comment]
@vtxf  Uncaught ReferenceError: data is not defined, I also get the error.

your can try it.

**Comment by vtxf** [comment]
> @vtxf Uncaught ReferenceError: data is not defined, I also get the error.
> 
> your can try it.

pls do not use ip address like 192.168.xxx.xxx.
use this: //127.0.0.1:xxx or //localhost:xxx
